---
- name: Install required packages
  apt:
    name: "{{ item }}"
    cache_valid_time: 86400  # 1 day
  with_items:
    - curl  # XXX may already be installed
    - python3-pip
    - python3-virtualenv
