---
# We only want one test_run_id per run (not one per client per run) which
#  prevents us from setting it in defaults/main.yml. We do, however, want
#  to be able to override it using other methods (like -e) so we check
#  whether it's defined before setting the variable
- name: Generate test_run_id
  set_fact:
    test_run_id: "{{ 2147483648 | random }}"  # 31 bits is enough!
  run_once: true  # Only want a single test_run_id, not one per client
  when: test_run_id is undefined

# Even though the fetch below task would create this directory, it's easier
#  to troubleshoot a results directory that doesn't have any csv files than
#  it is to troubleshoot a failed metadata creation step (dir not found) so
#  we explicitly create the directory
- name: Make local test output directory
  file:
    state: directory
    dest: "{{ local_test_results_directory }}/root/wifi-test-results/test-run-{{ test_run_id }}"
  delegate_to: 127.0.0.1
  run_once: True
  become: False

- name: Make test output directory on clients
  file:
    state: directory
    dest: "{{ remote_test_results_directory }}"

- name: "Run tests as run id: {{ test_run_id }} in group: {{ test_group_id }}"
  command: ./run.sh
    "{{ parallel_run_count }}"
    "-b {{ test_bandwidth_bps }}"
    "-d {{ remote_test_results_directory }}"
    "http://{{ test_server_hostname }}/{{ test_file_path }}"
  args:
    chdir: "{{ script_dest_dir }}"  # downloader.py is expected next to run.sh
  async: "{{ test_max_duration_mins * 60 }}"  # async is in secs
  poll: 10

- name: Find results files
  command: "find {{ remote_test_results_directory }} -name '*.csv' -cmin -{{ test_max_duration_mins }}"
  register: results_files

- name: Fetch results files
  fetch:
    src: "{{ item }}"
    dest: "{{ local_test_results_directory }}/{{ item }}"
    flat: yes
  with_items: "{{ results_files.stdout_lines }}"

- name: Write run metadata
  template:
    src: metadata.ini.j2
    dest: "{{ local_test_results_directory }}/root/wifi-test-results/test-run-{{ test_run_id }}/metadata.ini"
  delegate_to: 127.0.0.1
  run_once: True
  become: False
