---

# Check early on to see whether the OS needs to be
# rebooted to allow a disk expansion step to complete.
# This is Armbian only, but the check doesn't hurt others.
- name: Check for resize2fs reboot oracle
  stat:
    path: "/var/run/resize2fs-reboot"
  register: resize2fs_reboot

# If the oracle above exists then we shouldn't continue
- name: Fail when disk expansion is incomplete
  fail:
    msg: "The system must be rebooted because the disk expansion is not complete!"
  when: resize2fs_reboot.stat.exists == True

# This is correct for test clients
- name: Set hostname based on inventory
  hostname:
    name: "{{ inventory_hostname }}"

- name: Set timezone to Sydney
  file:
    state: link
    src: /usr/share/zoneinfo/Australia/Sydney
    dest: /etc/localtime

- name: Install required packages
  apt:
    name: "{{ item }}"
    cache_valid_time: 604800  # 1 week
  with_items:
    - wget
    - python3-pip
    - python3-virtualenv

