---
- hosts: clients
  become: yes
  roles:
    - { role: setup-system, tags: ["setup-system"] }
    - { role: deploy-artifacts, tags: ["task_execution"] }
    - { role: execute-test, tags: ["task_execution"] }
